/**
 * vite-plugin-htaccess.ts
 * Gera .htaccess com regras de redirecionamento (301/302/307/410) a partir
 * do arquivo redirects.json, preservando o fallback SPA.
 *
 * Executa durante o build e grava em /dist/.htaccess.
 */

import type { Plugin } from "vite";
import fs from "fs";
import path from "path";

interface RedirectRuleJson {
  sourceUrl: string;
  targetUrl: string;
  type: number;
  isRegex: boolean;
  enabled: boolean;
}

interface RedirectCatalog {
  rules: RedirectRuleJson[];
}

function readRedirectRules(outDir: string): RedirectRuleJson[] {
  const candidates = [
    path.join(outDir, "data", "redirects.json"),
    path.join(process.cwd(), "public", "data", "redirects.json"),
  ];

  for (const filePath of candidates) {
    if (fs.existsSync(filePath)) {
      try {
        const raw = fs.readFileSync(filePath, "utf-8");
        const parsed = JSON.parse(raw) as RedirectCatalog;
        if (Array.isArray(parsed.rules)) return parsed.rules;
      } catch {
        // continua para o próximo candidato
      }
    }
  }
  return [];
}

/** Escapa caracteres especiais de regex para uso literal no .htaccess */
function escapeRewritePattern(source: string): string {
  // Remove leading slash for RewriteRule pattern
  const withoutLeading = source.startsWith("/") ? source.slice(1) : source;
  // Escapa caracteres especiais do Apache, exceto se já é regex
  return withoutLeading
    .replace(/\./g, "\\.")
    .replace(/\s/g, "\\ ");
}

function buildRedirectRules(rules: RedirectRuleJson[]): string {
  const enabled = rules.filter((r) => r.enabled);
  if (enabled.length === 0) return "";

  const lines: string[] = [
    "# --- REDIRECT RULES (auto-generated by vite-plugin-htaccess) ---",
  ];

  for (const rule of enabled) {
    const sourceWithoutSlash = rule.sourceUrl.startsWith("/") ? rule.sourceUrl.slice(1) : rule.sourceUrl;
    const pattern = rule.isRegex ? sourceWithoutSlash : escapeRewritePattern(rule.sourceUrl);

    if (rule.type === 410) {
      lines.push(`# 410 Gone: /${sourceWithoutSlash}`);
      lines.push(`RewriteRule ^${pattern}/?$ - [G,L]`);
    } else {
      const target = rule.targetUrl.startsWith("http") ? rule.targetUrl : rule.targetUrl;
      lines.push(`# ${rule.type}: /${sourceWithoutSlash} -> ${target}`);
      lines.push(`RewriteRule ^${pattern}/?$ ${target} [R=${rule.type},L]`);
    }
  }

  lines.push("# --- END REDIRECT RULES ---");
  lines.push("");

  return lines.join("\n");
}

export function htaccessPlugin(): Plugin {
  let resolvedOutDir = "dist";

  return {
    name: "vite-plugin-htaccess",
    apply: "build",

    configResolved(config) {
      resolvedOutDir = config.build.outDir ?? "dist";
    },

    closeBundle() {
      const rules = readRedirectRules(resolvedOutDir);
      const redirectBlock = buildRedirectRules(rules);

      // Lê template base do public/.htaccess, se existir
      const templatePath = path.join(process.cwd(), "public", ".htaccess");
      let template = "";
      if (fs.existsSync(templatePath)) {
        template = fs.readFileSync(templatePath, "utf-8");
      }

      let output: string;

      if (template.includes("# --- REDIRECT RULES PLACEHOLDER ---")) {
        // Substitui placeholder no template
        output = template.replace("# --- REDIRECT RULES PLACEHOLDER ---", redirectBlock);
      } else if (template) {
        // Insere regras antes do fallback SPA
        const fallbackIndex = template.indexOf("# SPA Fallback");
        if (fallbackIndex > -1) {
          output = template.slice(0, fallbackIndex) + redirectBlock + "\n" + template.slice(fallbackIndex);
        } else {
          // Insere no início
          output = redirectBlock + "\n" + template;
        }
      } else {
        // Gera .htaccess completo
        output = [
          "RewriteEngine On",
          "",
          redirectBlock,
          "# SPA Fallback",
          "RewriteCond %{REQUEST_FILENAME} !-f",
          "RewriteCond %{REQUEST_FILENAME} !-d",
          "RewriteRule . /index.html [L]",
          "",
        ].join("\n");
      }

      const outputPath = path.join(resolvedOutDir, ".htaccess");
      fs.writeFileSync(outputPath, output, "utf-8");

      const enabledCount = rules.filter((r) => r.enabled).length;
      console.log(`[htaccess] .htaccess gerado (${enabledCount} regras de redirect)`);
    },
  };
}
