/**
 * vite-plugin-cloudflare-redirects.ts
 * Gera _redirects (Cloudflare Pages) com regras de redirecionamento
 * a partir do redirects.json, preservando o fallback SPA.
 *
 * Executa durante o build e grava em /dist/_redirects.
 * Funciona em paralelo com vite-plugin-htaccess.ts (Apache).
 *
 * Limitacoes do CF Pages _redirects:
 * - Nao suporta regex (regras com isRegex=true sao ignoradas com warning)
 * - Nao suporta status 410 Gone (usa 302 -> /gone como fallback)
 * - Maximo 2000 regras estaticas
 */

import type { Plugin } from "vite";
import fs from "fs";
import path from "path";

interface RedirectRuleJson {
  sourceUrl: string;
  targetUrl: string;
  type: number;
  isRegex: boolean;
  enabled: boolean;
}

interface RedirectCatalog {
  rules: RedirectRuleJson[];
}

function readRedirectRules(outDir: string): RedirectRuleJson[] {
  const candidates = [
    path.join(outDir, "data", "redirects.json"),
    path.join(process.cwd(), "public", "data", "redirects.json"),
  ];
  for (const filePath of candidates) {
    if (fs.existsSync(filePath)) {
      try {
        const raw = fs.readFileSync(filePath, "utf-8");
        const parsed = JSON.parse(raw) as RedirectCatalog;
        if (Array.isArray(parsed.rules)) return parsed.rules;
      } catch {
        // continua para o proximo candidato
      }
    }
  }
  return [];
}

/**
 * Converte regras do redirects.json para formato Cloudflare _redirects.
 * Formato CF: /source /target statusCode
 */
function buildCFRedirectRules(rules: RedirectRuleJson[]): string {
  const enabled = rules.filter((r) => r.enabled);
  if (enabled.length === 0) return "";

  const lines: string[] = [
    "# --- CF REDIRECT RULES (auto-generated) ---",
  ];

  for (const rule of enabled) {
    const source = rule.sourceUrl.startsWith("/") ? rule.sourceUrl : `/${rule.sourceUrl}`;

    if (rule.isRegex) {
      lines.push(`# AVISO: regex nao suportado no CF Pages, regra ignorada: ${source}`);
      continue;
    }

    if (rule.type === 410) {
      // CF nao suporta 410 — redireciona para /gone (302 temporario)
      // RedirectGuard.tsx tambem trata 410 client-side como fallback
      lines.push(`${source}  /gone  302`);
    } else {
      const target = rule.targetUrl.startsWith("/") || rule.targetUrl.startsWith("http")
        ? rule.targetUrl
        : `/${rule.targetUrl}`;
      lines.push(`${source}  ${target}  ${rule.type}`);
    }
  }

  lines.push("# --- END CF REDIRECT RULES ---");
  return lines.join("\n");
}

export function cloudflareRedirectsPlugin(): Plugin {
  let resolvedOutDir = "dist";

  return {
    name: "vite-plugin-cloudflare-redirects",
    apply: "build",

    configResolved(config) {
      resolvedOutDir = config.build.outDir ?? "dist";
    },

    closeBundle() {
      const rules = readRedirectRules(resolvedOutDir);
      const redirectBlock = buildCFRedirectRules(rules);

      // Le template do public/_redirects (copiado pelo Vite para dist/)
      const outputPath = path.join(resolvedOutDir, "_redirects");
      let template = "";

      if (fs.existsSync(outputPath)) {
        template = fs.readFileSync(outputPath, "utf-8");
      }

      let output: string;

      if (template.includes("# --- CF REDIRECT RULES PLACEHOLDER ---")) {
        // Substitui placeholder no template
        output = template.replace("# --- CF REDIRECT RULES PLACEHOLDER ---", redirectBlock);
      } else if (template) {
        // Insere regras antes do SPA fallback
        const fallbackIndex = template.indexOf("/*  /index.html  200");
        if (fallbackIndex > -1) {
          output = template.slice(0, fallbackIndex) + redirectBlock + "\n\n" + template.slice(fallbackIndex);
        } else {
          output = template + "\n" + redirectBlock;
        }
      } else {
        // Gera _redirects completo (fallback se template nao existe)
        output = [
          "# Auto-generated by vite-plugin-cloudflare-redirects",
          "",
          "/admin    /  301",
          "/admin/*  /  301",
          "",
          redirectBlock,
          "",
          "# SPA Fallback",
          "/*  /index.html  200",
          "",
        ].join("\n");
      }

      // Normaliza line endings para LF (evita CRLF misto no Windows)
      output = output.replace(/\r\n/g, "\n");

      fs.writeFileSync(outputPath, output, "utf-8");

      const enabledCount = rules.filter((r) => r.enabled).length;
      const regexSkipped = rules.filter((r) => r.enabled && r.isRegex).length;
      console.log(`[cf-redirects] _redirects gerado (${enabledCount} regras, ${regexSkipped} regex ignoradas)`);
    },
  };
}
